format = """
[  ](fg:color_fg bg:color_bg)\
$nodejs\
$rust\
$golang\
$php\
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

palette = 'solarized_osaka'

[palettes.solarized_osaka]
color_fg = '#c0caf5'
color_bg = '#1a1b26'
color_blue = '#7aa2f7' #7dcfff #15161e #458588
color_aqua = '#689d6a'
color_green = '#9ece6a'
color_orange = '#d65d0e'
color_purple = '#bb9af7' #b16286
color_red = '#f7768e' #cc241d
color_yellow = '#e0af68' #d79921
color_white = '#a9b1d6'

[os]
disabled = false
style = "bg:color_fg fg:color_yellow"

[username]
show_always = true
style_user = "bg:color_bg fg:color_fg"
style_root = "bg:color_bg fg:color_fg"
format = '[ $user ]($style)'

[directory]
read_only = " 󰌾"
style = "color_fg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[character]
success_symbol = "[>](color_green)"
error_symbol = "[x](color_red)"
vimcmd_symbol = "[<](color_green)"

[git_state]
format = "[$branch]($style)"
style = "color_purple"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "color_aqua"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
format = "[$branch]($style)"
style = "color_yellow"
symbol = " "

[git_commit]
tag_symbol = '  '

[cmd_duration]
format = "[$duration]($style) "
style = "color_yellow"

[python]
format = "[$virtualenv]($style) "
style = "color_yellow"
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
