[colors]
foreground = "#FDF6E3"
background = "#00141A"
cursor_bg = "#FDF6E3"
cursor_border = "#FDF6E3"
cursor_fg = "#00141A"
selection_bg = "#FDF6E3"
selection_fg = "#00141A"

# very dark ansi = ["#073642", "#332700", "#5C220A", "#57100F", "#25285B", "#103956", "#103B3D", "#2C3300"]   
ansi = ["#586E75", "#664D00", "#A13C11", "#B7211F", "#494FB6", "#1B6497", "#1A6265", "#596600"]   
brights = ["#FDF6E3", "#FFE999", "#FF9468", "#FF9D9B", "#CCCFFF", "#AADCFF", "#B9FFFA", "#D6FFAC"]

[colors.tab_bar]
inactive_tab_edge = "#103956"
background = "#1B6497"

[colors.tab_bar.active_tab]
fg_color = "#AADCFF"
bg_color = "#268BD2"

[colors.tab_bar.inactive_tab]
bg_color = "#1B6497"
fg_color = "#49AEF5"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#103956"
fg_color = "#49AEF5"

[colors.tab_bar.new_tab_hover]
bg_color = "#103956"
fg_color = "#49AEF5"

[colors.tab_bar.new_tab]
bg_color = "#103956"
fg_color = "#49AEF5"

[metadata]
aliases = []
author = "craftzdog"
name = "Solarized Osaka Base"
